#!/usr/bin/env python3

# Still to do:
# * Be compatible with Python 2.X
# * Check if the layer already exists with a HEAD request
# * Handle Authentification

from tempfile import TemporaryDirectory
import tarfile
import sys
import os
import hashlib
import json
from os.path import join
from http.client import HTTPConnection, HTTPSConnection

def compute_digest(filename):
    sha256_hash = hashlib.sha256()
    with open(filename, "rb") as f:
        for byte_block in iter(lambda: f.read(4096), b""):
            sha256_hash.update(byte_block)
    return "sha256:" + sha256_hash.hexdigest()


def parse_dst(dst):
    """
    >>> parse_dst('http://registry:5000/my/repository')
    {'https': False, 'host': 'registry:5000', 'path': '/v2/my/repository/'}
    >>> parse_dst('http://registry:5000/my/repository/')
    {'https': False, 'host': 'registry:5000', 'path': '/v2/my/repository/'}
    >>> parse_dst('registry/my/repository/')
    {'https': True, 'host': 'registry:5000', 'path': '/v2/my/repository/'}
    >>> parse_dst('registry:5000/my/repository/')
    {'https': True, 'host': 'registry:5000', 'path': '/v2/my/repository/'}
    """
    if not dst.startswith("http://") and not dst.startswith('https://'):
        dst = "https://" + dst

    if dst.startswith("https://"):
        is_http = True
        dst = dst[8:]
    else:
        is_http = False
        dst = dst[7:]

    dst = dst.rstrip("/") + "/"

    p = dst.find('/', dst.find('//') + 2)
    dst = dst[:p] + "/v2" + dst[p:]

    host = dst.split('/')[0]
    if host.find(':') == -1:
        host = host + ':5000'

    return {
        "https": is_http,
        "host": host,
        "path": dst[dst.find('/'):]
    }


def perform_request(method, registry, path, body=None, headers={}):
    """
    See also: https://mail.python.org/pipermail/web-sig/2007-April/002662.html
    """
    response = None
    try:
        full_path = registry['path'] + path
        print("> ", method, registry['host'], full_path)
        h = HTTPSConnection(registry['host']) if registry['https'] else HTTPConnection(registry['host'])
        h.request(method, full_path, body, headers)
        response = h.getresponse()
    finally:
        if response != None:
            data = response.read()
            if len(data) > 0 and response.getcode() not in [201, 202]:
                print(data)
        h.close()
    print("    Return:", response.getcode())
    return response


def upload_blob(registry, src_f, media_type):
    print("* Uploading " + src_f)
    r = perform_request('POST', registry, 'blobs/uploads/')
    location = r.headers['Location']
    # TODO: extract and unit test
    location_no_root = location[location.find(registry['path']) + len(registry['path']):]
    with open(src_f, "rb") as content_file:
        content = content_file.read()
    location_with_digest = location_no_root[:location_no_root.find('?')+1] + 'digest=' +compute_digest(src_f)+'&'+location_no_root[location_no_root.find('?')+1:]
    r = perform_request(
        'PUT',
        registry,
        location_with_digest,
        content,
        {'Content-Type': 'application/octet-stream', 'Content-Length': str(len(content))} # 'application/octet-stream'
    )
    # print(r.getcode())
    # print(r.headers)
    return

def upload_manifest(registry, manifest):
    """curl -v -X PUT http://registry.default.svc.cluster.local:5000/v2/bourse/back/manifests/latest -H "Content-Type: application/vnd.docker.distribution.manifest.v2+json" -d @toto.json"""
    print("* Uploading manifest")
    headers = {
        'Content-Type': 'application/vnd.docker.distribution.manifest.v2+json'
    }
    r = perform_request('PUT', registry, 'manifests/latest', manifest, headers)


def get_file_size(f):
    return os.path.getsize(f)


"""
{
  "config": {
    "digest": "sha256:1358ac6604c5bd5e41ec8b7b633be90ae8f643f791e51f8646c0746874f4a9fa",
    "mediaType": "application/vnd.docker.container.image.v1+json",
    "size": 458
  },
  "layers": [
    {
      "digest": "sha256:8f125ded1b483229a567e48eece98cc8867c2bee55fb73e9cd65ceecc448b7c7",
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "size": 7689429
    }
  ],
  "mediaType": ,
  "schemaVersion": 2
}
"""


def build_manifest(config_f, layers_f):
    json_d = {}
    json_d['schemaVersion'] = 2
    json_d['mediaType'] = 'application/vnd.docker.distribution.manifest.v2+json'
    json_d['config'] = {
        'digest': compute_digest(config_f),
        'size': get_file_size(config_f),
        'mediaType': 'application/vnd.docker.container.image.v1+json'
    }
    json_d['layers'] = []
    for layer_f in layers_f:
        # TODO: check the layer is indeed compressed
        json_d['layers'].append({
            'digest': compute_digest(layer_f),
            'size': get_file_size(layer_f),
            'mediaType': "application/vnd.docker.image.rootfs.diff.tar.gzip"
        })
    return json.dumps(json_d)


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print("docker-push source destination")
        print("  Example: docker-push my-image http://registry:5000/my-repository")
        exit(1)

    src = sys.argv[1]
    assert os.path.isfile(src), src + " is not a file / does not exist"
    repository_url = parse_dst(sys.argv[2])

    with TemporaryDirectory() as temp_dir:
        try:
            t = tarfile.TarFile(src)
        except tarfile.ReadError as e:
            print("Failed. Is " + src + " an Docker image?")
            sys.exit(1)
        t.extractall(temp_dir)
        manifest_path = os.path.join(temp_dir, "manifest.json")
        with open(manifest_path, "r") as manifest_file:
            manifest = json.load(manifest_file)
            config_f = join(temp_dir, manifest[-1]['Config'])
            layers_f = [join(temp_dir, l) for l in manifest[-1]['Layers']]
        manifest = build_manifest(config_f, layers_f)
        # TODO : lister les layers
        # TODO : uploader la config
        # TODO: recréer le manifest
        upload_blob(repository_url, config_f, 'application/vnd.docker.container.image.v1+json')
        for layer_f in layers_f:
            upload_blob(repository_url, layer_f, 'application/vnd.docker.image.rootfs.diff.tar.gzip')
        upload_manifest(repository_url, manifest)